linters:
  enable-all: true
  disable:
    - deadcode
    - nosnakecase
    - exhaustivestruct
    - maligned
    - golint
    - structcheck
    - ifshort
    - varcheck
    - scopelint
    - interfacer
    - depguard
    - gomnd
    - goerr113
    - testpackage
    - paralleltest
    - exhaustruct
    - varnamelen
